Samsung/WATT

CONTRIBUTING.md
README.md

Some urls in md files were taking users to unauthorized page.
Now these urls are fixed to right pages.
Signed-off-by: ws29.jung <ws29.jung@samsung.com>

Fix URLs in md files

---

views/index.ejs

Fix wrong text and url on index page

---

hooks/pre-commit
package.json

- Added shared-git-hooks module
- Added pre-commit logic

Append pre-commit to check code whether it is correct or not

---

package.json

https://github.com/Samsung/WATT/wiki/Release-Notes#release-note-050

[Release] WATT 0.5.0

---

test/index.js

- add logout tests
- coverage for /routes/index.js is increased 82.5% -> 100%

Improve test coverage of /routes/index.js

---

.csslintrc
Gruntfile.js
libs/brackets-server/embedded-ext/.csslintrc

Revert "Apply csslint rule to allow IDs in selectors"

---

.travis.yml
README.md

- Add '.travis.yml' to connect travis-ci
- Add badge to check build status on the README

Connect travis-ci to check build status

---

app.js
test/appserverTest.js

- test cases for app.js are implemented.
- branch condition for NODE_ENV is not covered by this patch yet.
- in order to increase test coverage, app.js is refactored slightly.

Add test cases for app.js

---

launch

- Add option to install NaCl SDK

Change script to install NaCl SDK

---

test/bracketsExtTest.js

Basic test code for brackets-ext is implemented.

Add unit test for /routes/brackets-ext.js

---

package.json

https://github.com/Samsung/WATT/wiki/Release-Notes#release-note-051

[Release] WATT 0.5.1

---

libs/brackets-server/embedded-ext/importfile/main.js
libs/brackets-server/embedded-ext/importfile/nls/ko/strings.js
libs/brackets-server/embedded-ext/importfile/nls/root/strings.js
libs/brackets-server/embedded-ext/importfile/node/ImportDomain.js
libs/brackets-server/hacks/src/command/DefaultMenus.js

- Add copy, cut and paste context menu
- Add strings for new menu
- Remove unnecessary "Navigate show in OS" menu

Implement copy, cut and paste

---

libs/brackets-server/embedded-ext/project/main.js

Show loading dialog when packaging wgt file

---

public/js/project.js
routes/project.js
views/modals/newproject.ejs

Add checkbox to create empty project

---

package.json

https://github.com/Samsung/WATT/wiki/Release-Notes#release-note-052

[Release] WATT 0.5.2

---

libs/brackets-server/embedded-ext/apiviewer/main.js
libs/brackets-server/embedded-ext/file-extension/main.js

There was a bug with file view on side bar
which did not update file/directory change on real time.
Now when file/directory changes, it will refresh the side bar and update.
Also there were several eslint with apiviewer and now there are fixed.
Signed-off-by: ws29.jung <ws29.jung@samsung.com>

fixup! Support API outline for WASM idls

---

test/bracketsTest.js

- Implement basic test cases for /routes/brackets.js
- .gz compression condition is not covered yet

Add unit test for /routes/brackets.js

---

test/bracketsTest.js

Replace chai.request to agent on bracketsTest.js

---

package.json

https://github.com/Samsung/WATT/wiki/Release-Notes#release-note-053
Signed-off-by: ws29.jung <ws29.jung@samsung.com>

[Release] WATT 0.5.2 (#50)

---

Gruntfile.js
libs/brackets-server/embedded-ext/hirse.beautify/LICENSE
libs/brackets-server/embedded-ext/hirse.beautify/default.jsbeautifyrc
libs/brackets-server/embedded-ext/hirse.beautify/main.js
libs/brackets-server/embedded-ext/hirse.beautify/nls/ko/strings.js
libs/brackets-server/embedded-ext/hirse.beautify/nls/root/strings.js
libs/brackets-server/embedded-ext/hirse.beautify/nls/strings.js
libs/brackets-server/embedded-ext/hirse.beautify/package.json
libs/brackets-server/embedded-ext/hirse.beautify/strings.js
libs/brackets-server/embedded-ext/hirse.beautify/thirdparty/beautify-css.js
libs/brackets-server/embedded-ext/hirse.beautify/thirdparty/beautify-html.js
libs/brackets-server/embedded-ext/hirse.beautify/thirdparty/beautify.js

It makes minified script to be beautified code.

Add beautify extension

---

README.md
views/header.ejs
views/index.ejs
views/modals/newproject.ejs

Signed-off-by: jinwoo jeong <jw00.jeong@samsung.com>

Use 'WebAssembly', without no blank.

---

views/header.ejs

Change from 'WebAssmbly' to 'WebAssembly' in views/header.ejs
Signed-off-by: hyunduk.kim <hyunduk.kim@samsung.com>

Fix a typo

---

.eslintrc
Gruntfile.js
libs/brackets-server/.eslintrc
libs/brackets-server/embedded-ext/ConfigXmlEditor/main.js
libs/brackets-server/embedded-ext/ConfigXmlEditor/scripts/CategoriesManager.js
libs/brackets-server/embedded-ext/ConfigXmlEditor/scripts/FeatureList.js
libs/brackets-server/embedded-ext/ConfigXmlEditor/scripts/PrivilegeList.js
libs/brackets-server/embedded-ext/apiviewer/main.js
libs/brackets-server/embedded-ext/brackets-indent-guides/nls/strings.js
libs/brackets-server/embedded-ext/file-extension/node/ImportDomain.js
libs/brackets-server/embedded-ext/hirse.beautify/main.js
libs/brackets-server/embedded-ext/hirse.beautify/nls/ko/strings.js
libs/brackets-server/embedded-ext/hirse.beautify/nls/root/strings.js
libs/brackets-server/embedded-ext/hirse.beautify/nls/strings.js
libs/brackets-server/embedded-ext/hirse.beautify/strings.js
libs/brackets-server/embedded-ext/pwe/node/PWEDomain.js
libs/brackets-server/embedded-ext/pwe/template/service-worker-push.js
libs/brackets-server/embedded-ext/pwe/template/service-worker-register.js
libs/brackets-server/embedded-ext/tizen-profile/main.js
public/js/project.js

- Add the 'quotes' option to enable quotes validation
- Add the 'avoidEscape' option to allow some exceptions
(https://eslint.org/docs/rules/quotes#avoidescape)
- Fix wrong quotes

Enable quotes validation

---

launch
libs/brackets-server/Gruntfile.js
libs/brackets-server/embedded-ext/brackets-minify/LICENSE
libs/brackets-server/embedded-ext/brackets-minify/README.md
libs/brackets-server/embedded-ext/brackets-minify/main.js
libs/brackets-server/embedded-ext/brackets-minify/nls/root/strings.js
libs/brackets-server/embedded-ext/brackets-minify/nls/strings.js
libs/brackets-server/embedded-ext/brackets-minify/node/minifycss.js
libs/brackets-server/embedded-ext/brackets-minify/node/minifyjs.js
libs/brackets-server/embedded-ext/brackets-minify/node/package.json
libs/brackets-server/embedded-ext/brackets-minify/package.json
libs/brackets-server/embedded-ext/brackets-minify/strings.js
libs/brackets-server/embedded-ext/hirse.beautify/main.js

- To support minify feature, add 'brackets-minify' extension.
- Move menu divider from 'hirse.beautify' to the 'brackets-minify'

Add 'brackets-minify' extension

---

libs/brackets-server/embedded-ext/client-fs/lib/file-system.js

Unreviewed. Fix build break after #66

---

libs/brackets-server/embedded-ext/wasm-debug/main.js
libs/brackets-server/embedded-ext/wasm-debug/nls/ko/strings.js
libs/brackets-server/embedded-ext/wasm-debug/nls/root/strings.js
libs/brackets-server/embedded-ext/wasm-debug/node/DebugDomain.js

- Add strings for "wast->wasm" menu
- Check whether project have a converted file with same name

Implement "wast->wasm" menu

---

test/update.js

- Check '/update' GET method API
- Check '/update/template' POST method API

Add unit test for the 'route/update.js'

---

libs/brackets-server/embedded-ext/project/node/CompileDomain.js

Some of functions used for the test are recovered to the
original state because the test is carried out based on
the passed path.

Fix test failure after #72

---

test/exportTest.js

- coverage is increased : 15.48% -> 77.38%
- some path related test condition is not covered by this patch yet.

Add unit test for routes/export.js

---

libs/brackets-server/embedded-ext/project/main.js
libs/brackets-server/embedded-ext/project/nls/root/strings.js
libs/brackets-server/embedded-ext/project/node/CompileDomain.js

- Modify title of wgt packing from build to pack
- rename related string and function name

Correct title of dialog for wgt packaging.

---

libs/brackets-server/Gruntfile.js
libs/brackets-server/hacks/patch/0001-Fix-module-not-found-issue-after-71.patch

- Remove unused "StaticServer" from the default extension
- Remove unnecessary code that I missed from #71

Fix module not found issue after #71

---

launch
libs/brackets-server/Gruntfile.js
libs/brackets-server/hacks/patch/0001-Add-BinaryView-in-order-to-present-selction-of-wasm-.patch

. move grunt build after set grunt path to environment variable
. show error message when fail to apply git patch

Fix build error

---

public/css/style.css
public/js/project.js
views/parts/projectlist.ejs

- Show overlay image if your mouse is over the project title
- Add some styles for the "btn-app" buttons to make it beautiful

Add hover image to improve usability

---

.travis.yml
launch

Used default OSX image and python2 environment

Fix travis build break caused by mongodb installtion on OSX

---

libs/brackets-server/Gruntfile.js
libs/brackets-server/package.json
package.json

The 'brackets-server' used the old verison, so I changed
it to use the latest version.

Change the 'socket.io' version to use the latest version

---

models/project.js
routes/brackets.js
views/parts/projectlist.ejs

Update project modified time when editing project information
or opening the project.

Add updated time to check the project's changed time

---

views/parts/projectlist.ejs

If the project doesn't have an image, replace it with
a placeholder image

Add project placeholder image

---

package.json

Release WATT 0.6.0
Includes
- WAST -> WASM translation
- fixes and improvements

Release WATT 0.6.0

---

.travis.yml
launch

[Issue] https://github.com/Samsung/WATT/issues/102
[Problem] brackets test are failing
[Solution] Run tests after launch -d

Run tests in travis after launch

---

README.md
docker-compose-aws.yml
ecs-params.yml

[Issue] N/A
[Problem] Lack of information how to set up WATT instance on AWS
[Solution] Update README.md

[Docker] Update README.md

---

libs/brackets-server/embedded-ext/project/main.js

[Issue] N/A
[Problem] When opening project, nothing is opened
[Solution] Read mian project file name from config.xml
and open it

Open main project file in editor when opening project

---

libs/util.js
routes/demos.js
routes/project.js

[Issue] N/A
[Problem] eslint errors intoduced in:
- https://github.com/Samsung/WATT/pull/119
- https://github.com/Samsung/WATT/pull/120
[Solution] Fix eslint errors

eslint fixes after latest changes

---

libs/brackets-server/embedded-ext/file-extension/node/ImportDomain.js

[Issue] N/A
[Problem] Too much server info shown on error
[Solution] Change info dialog for import package

Change import package info dialog

---

libs/util.js
routes/brackets.js
routes/project.js

[Issue] http://suprem.sec.samsung.net/jira/browse/TIZENWF-2613
[Problem] User 'foo' can open and modify projects of user 'bar'
[Solution] Before opening project, check if project is owned
by current user.
[TEST]
1. Sing up and log as foo@watt.com
2. Create sample web application.
3. Open newly created project and copy URL.
4. Logout.
5. Sing up and log as bar@watt.com
6. Paste copied URL.
7. 'Forbidden' should be displayed.

Allow user to open his projects only

---

test/demosTest.js

[Issue] N/A
[Problem] No test for demos
[Solution] Add basic demos tests

Add basic demos tests

---

.travis.yml
package.json

Signed-off-by: Kornelia Kobiela <k.kobiela@samsung.com>

Update nyc dependency

---

README.md

[Docker] Add information how to create new AWS instance

---

package.json

[Problem] loading TAU samples takes takes too long
[Solution] Update relese version  Changes included in this release:
- Ubuntu packages upgrade on docker due to security
- Open TAU samples from localhost

WATT 0.7.1 Release

---

Dockerfile
launch

Contains two commits:
- [Docker] Bypass third party libs
- Add option to bypass emscripten

[Docker] Bypass third party libs

---

package.json

Changes since 0.7.1 release:
db42b9c Update TAU/1.1 submodule to 1.1.6 version
3c4c9ac Update Design Editor submodule to 0.7.1 version
4231359 Update TAU and samples to 1.1.5 version
387d606 [Docker] Simultaneous docker image push
17dc086 Update Design Editor submodule to 0.7.0 version
bb0b3f9 Update TAU 1.0 to 1.0.7
4902543 [Docker] Bump mongod version to 4.2
d7f9891 Update TAU to version 1.1.4
0c34a6c Fix "NameError: global name 'install_deb_package' is not defined"
3c52f20 Unify mongodb version usage and remove Ubuntu 14.04 support
cdc9583 Add support for Ubuntu 18.04
2232b92 [Docker] Bypass third party libs
e2049d5 Add option to bypass emscripten
562e555 Restore "Pack to WGT package" ctx menu for remote samples
3354699 Templates & TAU: Source of TAU library has changed
97eb4d1 …

WATT 0.8.0 release

---

.travis.yml

[Issue] #190
[Problem]  ./launch -d -n update command fails
[Solution] Bypass emscripten download

 Bypass emscripten download for travis 

---

package.json

Changes since 0.8.0:
473190c Bypass emscripten download for travis
5e7c48f Update TAU libraries

 WATT 0.8.1 release

---

package.json

Changes since 0.8.1:
37c0aba Update TAU 1.1 to 1.1.11 version

WATT 0.8.2 release

---

package.json

Changes in 0.8.3:
c0b8c1c Update TAU libraries

WATT 0.8.3 release

---

routes/demos.js
routes/export.js
routes/import.js
routes/project.js
routes/update.js

Signed-off-by: cookie <cookie@samsung.com>

Fix the Svace issue

---

routes/brackets.js

[Issue] N/A
[Problem] const variable was moified
[Solution] Changed modificaiton to let

Fix static analysis issue

---

libs/device-plugin-manager.js
routes/demos.js

Fix return value for demos.js
Use ensureDir instead of mkdir

Fix static analysis issues

---

libs/util.js

[Issue] N/A
[Problem] Return statement not used consistently
[Solution] Add missing return statements

 Fix missing return statements in utils.js 

---

app.js

[Issue] N/A
[Problem] Minor static analysis issues
[Solution] Added missing return statement. Fixed condition check.

 Fix static analysis issues in app.js 

---

routes/project.js

Issue:N/A
Problem : function is project.js does not return value consequently
Solution : avoid using return with no value
Signed-off-by: cookie <cookie@samsung.com>

Fix return value for project.js

---

routes/export.js
routes/import.js

Issue: N/A
Problem: fuction doesn't return value consequently
Solution: avoid using return with no value
Signed-off-by: cookie <cookie@samsung.com>

Fix return value for import.js and export.js

---

sample/web/TAU_1.1_Base_Mobile/index.html

[Issue] https://github.com/Samsung/TAU/issues/515
[Problem] TAU template has changed
[Solution] Apply changes from https://github.com/Samsung/TAU/pull/516

Sync changes in TAU 1.1 with sample

---

package.json

Changes in 0.8.4:
fd03ea55 Upversion DE to 0.0.8 version
ef889a4e Let launch script build TAU
3af29b64 Update TAU 1.0 submodule
e1d8eee8 Update TAU 1.1 in WATT
a2a39a02 Sync changes in TAU 1.1 with sample
fe7b094f Fix static analysis issues (#213)
7ffbb3b0 Fix return value for import.js and export.js (#212)
cbd70606 Fix return value for project.js (#211)
8575acab Fix static analysis issues in app.js
d308b6ba Fix return statements in utils.js
5ea16287 Fix return value for demos.js
f72163a3 Use ensureDir instead of mkdir
2a85da3e Fix static analysis issue
37501ae2 Fix the Svace issue (#204)

WATT 0.8.4 release

---

package.json

Changes in 0.8.5:
44e229c1 Add TAU/1.2

WATT 0.8.5 release

---

package.json

Changes in 0.8.6:
aed487db Remove Tizen Studio support from docker

WATT 0.8.6 release
