- app.js
Two DeprecationWarnings caused by npm test were fixed.
- open() is deprecated in mongoose >= 4.11.0, use openUri() instead, or set the useMongoClient option if using connect() or createConnection()
- mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead
> Fix mongoose and promise warings for npm test

- libs/brackets-server/embedded-ext/about/nls/ko/strings.js
For the korean version of about dialog menu, proper url strings are updated for WATT.
> Fix WATT url strings on about menu

- launch
"platform.linux_distribution()" returned wrong information if using
virtualenv for python dev development. So I change a way to get
correct information using the "lsb_release".
> Return wrong distribution information on running the "launch"

- launch
Curl is needed to install node but it is not default installed
package. So we need to install curl before installing the node.
> Modify launch script to install curl package

- launch
Fail to install WATT using launch script when we don't have
pip package. To install pip correctly, check the pip whether
it is existed and install it.
> Modify launch script to install pip package

- Makefile
- package.json
: run test on CI server with defined set of tests
: run test based on capabilities (optional features such as Tizen wgt packaging)
Introduce test Makefile for selective testing.
Makefile checks for optional feature (tizen) and run proper test script.
Signed-off-by: Andy Cho <sung.h.cho@samsung.com>
> Optional testing mechanism is needed for several reasons

- libs/brackets-server/Gruntfile.js
Add implementation to check whether detected file item is directory on the addEmbeddedExtesions() function.
Hence only directory will be added as an embedded extension.
> Fix build error for grunt build on brackets_server

- launch
Using magic strings/numbers is a potential risk.
I only changed the OS names used repeatedly.
Additionally I fixed a typo, 'unsupport'.
Signed-off-by: jinwoo jeong <jw00.jeong@samsung.com>
> Use constant variables for OS Names

- libs/brackets-server/embedded-ext/about/main.js
Commands.HELP_ABOUT menu is not existed so it makes some error when
launching the brackets. To fix error, add the menu item directly.
> Fix help.out not found issue

- libs/brackets-server/embedded-ext/importfile/nls/ko/strings.js
- libs/brackets-server/embedded-ext/importfile/nls/root/strings.js
'into folder' is named as INTO_FOLDER_lABEL.
It needs to be fixed to INTO_FOLDER_LABEL for 2 reasons :
- All other characters are in capital except 'l'.
- In [1], it is used as INTO_FOLDER_LABEL.
[1] libs/brackets-server/embedded-ext/importfile/htmlContent/Import-File.html
Signed-off-by: hyunduk.kim <hyunduk.kim@samsung.com>
> Fix the define of 'into folder'

- .travis.yml
Permission denined error occurred when installing the pip packages.
To fix error, add user option to the pip install.
> Fix 'pip install' error on travis

- launch
- package.json
- routes/brackets.js
- add grunt build for brackets-server when launch is working as dry-run mode
: some tests wants to scratch build of brackets-server
- add mock http for a test case that is using node module of http
: travis does not support local http server connection by itself
> Add implementation to support unit test on travis-ci

- .eslintrc
- libs/brackets-server/.eslintrc
Add 'sort-vars' option to check whether the variable
names are sorted alphabetically or not.
> Enable 'sort-vars' option

- libs/brackets-server/embedded-ext/dndfile/main.js
- libs/brackets-server/embedded-ext/file-extension/main.js
Some files are broken when importing files on WATT.
To fix it, read file as array buffer and refresh file
after importing files.
> Fix file import issue

- launch
- libs/brackets-server/Gruntfile.js
- libs/brackets-server/embedded-ext/file-extension/main.js
- libs/brackets-server/embedded-ext/wasm-debug/main.js
- libs/brackets-server/embedded-ext/wasm-debug/nls/ko/strings.js
- libs/brackets-server/embedded-ext/wasm-debug/nls/root/strings.js
- libs/brackets-server/embedded-ext/wasm-debug/nls/strings.js
- libs/brackets-server/embedded-ext/wasm-debug/node/DebugDomain.js
- libs/brackets-server/embedded-ext/wasm-debug/strings.js
- libs/brackets-server/hacks/app.js
- Add 'wabt' tool to analyze wasm file
- Add 'wasm -> wast' menu to translate file from wasm to wast
- Move 'convertRelativePath' function to the brackets util
> Implement wasm-debug extension

- libs/brackets-server/embedded-ext/ConfigXmlEditor/scripts/UpdateManager.js
- libs/brackets-server/embedded-ext/ConfigXmlEditor/scripts/XMLReadManager.js
- libs/brackets-server/embedded-ext/ConfigXmlEditor/scripts/XMLUtils.js
Change the function from 'createElement' to the 'createElementNS' to
create element with correct namespace
> The elements with the wrong namespace were generated on some browsers

- libs/brackets-server/Gruntfile.js
Those extensions are not in use and can cause unintended problems
> Remove unnecessary extensions from brackets

- libs/brackets-server/embedded-ext/project/main.js
- libs/brackets-server/embedded-ext/project/node/CompileDomain.js
Generally, there is no problem in sending a project path to the "/projects",
but there is an issue where the path of the previous tab is changed incorrectly
after opening new tab. In order to correct the project path, I modified the path
to be generated with the project ID.
> Fix an issue where working with wrong path after opening a new tab

- launch
The 'pkg_resources' seems to output the different result
depending on the version. In order to fix issue, I change
the parsing method to use simple way.
> launch fails due to old setuptools version

- libs/brackets-server/Gruntfile.js
Some warning messages was generated when the uglify's beautifer
running on particularly large files. So I set the "max-line-len"
to the false to remove warning messages.
> Remove warning messages on building brackets

- .travis.yml
We are getting "Pip command not found" during travis build
on OSX. We need to add pip setup to the launch script. I
fixed the issue temporarily using the xcode 7.3 image until
I fixed issue.
> Fix travis build on OSX

- launch
We don't need to install modules for the 'brackets-src' to run
the server correctly. And by removing the 'legacy-bundling' option,
we can remove the duplicated node modules installation.
> Remove unnecessary node modules installation 

- launch
Change the execution of pip to the pip2 when the OS is OSX.
> Fix a problem where failing to install pip

- package.json
- views/project.ejs
- version 2.3.11 -> 2.4.2
- From package.json, dependency of admin-lte is specified to be compatable with 2.3.11.
Therefore, npm just installed 2.4.2. but, app.js is just replaced with adminlte.min.js on 2.4.2.
In order to fix load failure of app.min.js for admin-lte, the version of admin-lte is now modified
and related code is also modified.
> Apply the latest version of admin-lte module.

- launch
[Issue] N/A
[Problem] Unable to debug DE in WATT
[Cause] DE is always compiled in release mode
[Solution] Add option to skip DE compilation
> Add option to skip DE compilation

- .eslintrc
- libs/brackets-server/embedded-ext/project/test/test.js
- package.json
[Issue] http://suprem.sec.samsung.net/jira/browse/TIZENWF-2495
[Problem] npm test fails with one failing test
[Cause] cleanupCallback is asynchronous in result of [1] This causes failure of check being right after callback:
result.tmpDirCleanup(); expect(fs.existsSync(result.tmpDirPath)).to.be.false;
[Solution] Convert test to asynchronous one
[Remarks] New testing code uses async await. In order to pass eslint check eslint configuration changes needed to be done according to [2]
[1] https://github.com/raszi/node-tmp/issues/57
[2] http://quabr.com/43933907/eslint-parsing-error-parsing-error-unexpected-token
> Fix temp directory cleanup problem for .wgt packaging test

- Dockerfile
[Issue] http://suprem.sec.samsung.net/jira/browse/TIZENWF-2493
[Problem] Docker images is huge.
[Solution] Do not invoke launch script while building docker images.
This means that launch script will be called once container
starts. This approximately takes two hours. This might be
issue once container for some reason needs to be restarted
resulting in no WATT availability during container setup.
> Move invoking launch script when container starts

- app.js
- libs/util.js
- routes/demos.js
[Issue] http://suprem.sec.samsung.net/jira/browse/TIZENWF-2199
[Problem] To open any project/sample user has to be authenticated.
It's required from WATT to allow opening the requested
sample without authentication, for example,
http://WATT_address:3000/demos/TAUBaseApplication/wearable/3.0/web
[Solution] Add rest API "/demos" to create brackets project from sample (name/profile/version/type)
needs to be given. Add and authenticate anonymous user to open
brackets project.
[Remarks] After opening sample demo as anonymous it's possible
to open other user's projects by accessing /brackets/projectId.
But this may be general issue (not strictly connected to anonymous user).
[TEST]
1. Open http://localhost:3000/demos/TAUBaseApplication/wearable/3.0/web
2. TAUBaseApplication application should …
> Add possibility to open WATT samples as anonymous user

- sample/web/TAUCheckboxApplication/config.xml
[Issue] N/A
[Problem] DE does not start for TAUCheckboxApplication
[Solution] Add config.xml to the project which was generated
from tizen studio cli.
> fixup! Add TAU CheckBox application to samples

- Dockerfile
- README.md
[Issue] N/A
[Problem] 'bower install && bower build' command waits for user response
while building DE.
[Solution] Use dedicated environemnt variable CI for bower. In addition, notes
to README.md are added how to update watt image.
[TEST] ./docker-run --rebuild
> [Docker] Stop bower from asking for statistics when installing

- README.md
- docker-compose-aws.yml
[Issue] N/A
[Problem] Lack of instruction how to set up aws instance in Asia region.
[Solution] Update README.md and docker-compose-aws.yml file.
> [Docker] Use Asia (Seoul) region while setting AWS

- Dockerfile
- config/default.json
- launch
- routes/demos.js
[Issue] http://suprem.sec.samsung.net/jira/browse/TIZENWF-2567
[Problem] WATT does not have all TAU samples
[Solution] Fetch TAU samples from https://samsung.github.io/TAU/examples/
while requesting /demos API with sample path as query parameter, for example
http://localhost:3000/demos/?path=mobile%2FUIComponents%2Fcomponents%2Fcontrols%2Fcheckbox.html
Since wget is used to download page, curl has been removed in favor of wget.
[TEST]
1. Create sample html with the following content:
<html>
<body>
<script>
window.open("http://localhost:3000/demos/?path=" + encodeURIComponent("mobile/UIComponents/components/controls/checkbox.html"));
</script>
</body>
</html>
Alternatively, you can manually encode path by replacing '/' with '%2F'.
2. Brackets project should be opened without user …
> Fetch TAU samples from TAU page

- libs/util.js
- models/config.xml
- routes/demos.js
- routes/project.js
[Issue] http://suprem.sec.samsung.net/jira/browse/TIZENWF-2567
[Problem] Deasign Editor does not start and tizen packaging does not
generate wgt file.
[Solution] Add config.xml and fill its content
[Remarks] Although config.xml is added, DE still does not start.
This issue is reported http://suprem.sec.samsung.net/jira/browse/TIZENWF-2580
[TEST]
1. Create sample html with the following content:
<html>
<body>
<script>
window.open("http://localhost:3000/demos/?path=" + encodeURIComponent("mobile/UIComponents/components/controls/checkbox.html"));
</script>
</body>
</html>
Alternatively, you can manually encode path by replacing '/' with '%2F'.
2. config.xml should exist in root directory.
> Add config.xml to downloaded TAU project

- .eslintignore
- .travis.yml
- package.json
Enable eslint verification in travis
[Issue] N/A
[Problem] No eslint verification in project
[Solution] Use lint-dfff from [1]
[1] https://www.npmjs.com/package/lint-diff
> Enable eslint verification in travis

- .travis.yml
[Issue] N/A
[Problem] When launch -d fails it is not reported by travis
[Reason] Travis reports failure only when jobs from script
section fail.
[Solution] Move launch to script section
> Fix launch check in travis

- config/docker.json
[Issue] N/A
[Problem] Unnecessary PORT definition since docker uses the same port number as
WATT which is taken from config/default.json.
[Solution] Remove PORT from config/docker.json
[TEST] ./docker-run.sh --rebuild
> Remove PORT from config/docker.json

- routes/demos.js
[Issue] N/A
[Problem] Can not open TAU samples for werable profile
[Solution] Fix typo werable -> wearable
[TEST]
1. Open http://localhost:3000/demos/?path=wearable%2FUIComponents%2Fcontents%2Fcontrols%2Fcheckbox.html
2. Brackets project should be opened and DE should display wearable profile.
> fixup! Fetch TAU samples from TAU page

- routes/demos.js
[Issue] N/A
[Problem] Empty brackets project is created once users passes
not valid path to TAU sample.
[Solution] Restore wget error checking which was reported https://github.com/Samsung/TAU/issues/77
[TEST positive]
1. Open http://localhost:3000/demos/?path=mobile%2FUIComponents%2Fcomponents%2Fcontrols%2Fcheckbox.html
2. Brackets project should be created and index.html should be opened.
[TEST negative]
1. Open http://localhost:3000/demos/?path=WRONGPATH.html
2. Error should be visible to user.
> Let wget report errors to user

- routes/demos.js
[Issue] N/A
[Problem] Some downloaded samples have missing references
[Solution] Ignore error when sample is referencing to not existing file.
Only stop when sample does not exist at all
>  Do not break when sample has not existing reference

- routes/demos.js
[Issue] N/A
[Problem] Entries in Number Picker example don't work
[Cause] html files are not downloaded by wget
[Solution] Add -r (recusrsive) option to wget download
[Test]
1. Visit localhost:3000/demos?path=wearable%2FUIComponents%2Fcontents%2Fcontrols%2Fnumberpicker%2Findex.html
2. Open DE
3. Click preview button
4. Click on Simple/Accelerated links
Expected:
Links should be working correctly
> Download resources recursively - Number Picker example fix

- public/js/project.js
- routes/project.js
[Issue] http://suprem.sec.samsung.net/jira/browse/TIZENWF-2611
[Poblem] User 'foo' can delete project created by user 'bar'.
[Solution] Check current user before deleting project.
In addition, prohibit anonymous user from deleting his
projects as they are expected to be removed by WATT itself (not implemented).
[TEST]
1. Sing up and login in as foo@watt.com.
2. Create sample web application (for example, TAUBaseApplication).
3. Open newly create project and copy its id.
4. Logout
5. Sing up and login in as bar@watt.com.
6. Create sample web application (for example, TAUBaseApplication).
7. Paste foo's project id into the code below
public/js/project.js
...
$('#delete-button').on('click', function() {
$.ajax({
url: '/project/'+ 'PROJECT_ID_FROM_FOO_USER',
...
8. Restart WATT.
9. Login in …
> Do not delete project owned by different user

- config/default.json
- routes/demos.js
[Issue] N/A 
[Problem] Disk usage increase.
[Solution] Add limitation to 100 projects for projects created by anonymous user. Once this
number is reached, anonymous projects older than one hour are deleted.
[TEST] Require no code/logic changes.
1. Open http://localhost:3000/demos/?path=mobile%2FUIComponents%2Fcomponents%2Fcontrols%2Fcheckbox.html
100 times.
2. Open http://localhost:3000/demos/?path=mobile%2FUIComponents%2Fcomponents%2Fcontrols%2Fcheckbox.html again
3. You should see 'No possible to create more demos. Please try again later.'
4. Wait one hour.
5. Open http://localhost:3000/demos/?path=mobile%2FUIComponents%2Fcomponents%2Fcontrols%2Fcheckbox.html
6. Sample should be opened.
> Clean outdated anonymous projects

- README.md
- docker-run.sh
[Issue] N/A
[Problem] Docker uses cached local resources while building images. This is potential
issue for user who already used docker for WATT. In this case
docker will not process them.
[Solution] Add --no-cache parameter. In addition, update README.md how to use
docker-run.sh.
> [Docker] Add --no-cache parameter to docker build

- docker-common.sh
- docker-run.sh
- docker-watt-image-push.sh
[Issue] N/A
[Problem] To push watt image to AWS repositories, docker-run.sh
script must be launched with --rebuild parameter and
user unnecessary has to wait for docker-compose up
(which runs docker image).
[Solution] Create docker-common.sh including common functionality
used by docker-run.sh and docker-watt-image-push.sh
> [Docker] Extract common functionality to separate script

- routes/demos.js
- test/demosTest.js
[Issue] https://github.com/Samsung/TAU/issues/188
[Problem] index.html is not opened
[Reason] Additional 2 directories on the path
[Solution] Take into account two additional directories on the path
[Test] Visit following examples and make sure that index.html is opened
http://localhost:3000/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fcontrols%2Fnumberpicker%2Findex.html
http://localhost:3000/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fcontrols%2Fcheckbox.html
http://localhost:3000/demos?path=1.0%2Fexamples%2Fmobile%2FUIComponents%2Fcomponents%2Fcontrols%2Fcheckbox.html
> Fix examples opening in WATT

- app.js
- views/error.ejs
[Issue] N/A
[Problem] In docker environment user can log in
[Solution] Check env variable and enable index site only for non-docker
environment
[Test]
1. Launch WATT
2. Visit localhost:3000 (no error)
3. Visit http://localhost:3000/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fcontrols%2Fnumberpicker%2Findex.html (no error)
4. Launch WATT in docker environment
5. Visit localhost:3000 (error)
6. Visit http://localhost:3000/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fcontrols%2Fnumberpicker%2Findex.html (no error)
> Disable login feature for docker

- README.md
- docker-watt-image-push.sh
[Issue] N/A
[Problem] User has to perform many actions manually
to push watt docker image to AWS repositories
[Solution] Let docker-watt-image-push.sh do this automatically.
[Test] ./docker-watt-image-push.sh AWS_ACCOUNT_ID
> [Docker] Push watt docker image to AWS repos

- libs/brackets-server/embedded-ext/about/htmlContent/about-watt-dialog.html
- package.json
[Problem] https://code.tizen.org has out dated (0.6.0) release version
[Solution] Update relese version. In addition, update copyright year in
About WATT dialog window.
> WATT 0.7.0 Release

- README.md
- watt-aws-update.sh
[Issue] N/A
[Problem] User has to manually restart WATT Task using AWS Console
[Solution] Modify the script to do this automatically.
> Restart WATT Task after image push

- Dockerfile
[Issue] N/A
[Problem] potential security vulnerability in outdated Ubuntu packages.
[Solution] Ubuntu upgrade.
[Test]
1. ./docker-run.sh --rebuild
2. Open http://localhost:3000/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fcontrols%2Fnumberpicker%2Findex.html
> [Docker] Ubuntu packages upgrade

- Dockerfile
[Problem] According to [1], April 2021 is end of support
[Solution] Upgrade Ubuntu to 18.04
[Test] ./docker-run --rebuild
docker ps (find contaitner id for watt)
docker container exec -i CONTAINERID lsb_release -a
You should see the following output:
Description:	Ubuntu 18.04.3 LTS
[1] https://wiki.ubuntu.com/Releases
> [Docker] Upgrade Ubuntu to 18.04

- .gitmodules
- routes/project.js
- sample/list.json
Issue: related to https://github.com/Samsung/WATT/issues/169
Problem: Templates are using common files eg. TAU libraries.
Update these modules requires too many actions.
Solution: Developer of DesignEditor can define files to includ in list.json
by new keyword "includes".
example:
```
"includes": [{
"src": "TAU/dist",
"dest": "lib/tau"
}]
```
Signed-off-by: Tomasz Lukawski <t.lukawski@samsung.com>
> Projects: Added includes feature to append files during the project creation

- libs/brackets-server/embedded-ext/project/main.js
- libs/brackets-server/embedded-ext/tizen-profile/main.js
[Problem] Lack of "Pack to WGT package" and "User certificate"
context menu options for remote samples.
[Solution] Add missing context menu options for "demo" project type.
[Test]
1. ./docker-run.sh --rebuild
2. Open http://localhost:3000/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fcontrols%2Fnumberpicker%2Findex.html
3. Chose "Profile" -> "User certificate" and create certificate.
4. You should see "Certificate saved succesfully".
5. Click OK.
6. Chose "Project" -> "Pack to WGT package".
7. You should see "Package has been successfully built".
8. Click OK.
9. On file tree, you should see "Tau Sample Demo.wgt".
> Restore "Pack to WGT package" ctx menu for remote samples

- launch
[Issue] https://github.com/Samsung/WATT/issues/174
[Problem] No support for Ubuntu 18.04
[Solution] Add 18.04 to supported list. Update GPK key for MongoDB
and add 18.04 specific MongoDb repo url.
> Add support for Ubuntu 18.04

- launch
[Issue] https://github.com/Samsung/WATT/issues/176
[Problem] Different MongoDB version used for different distributions
[Solution] Use MongoDB version for Ubuntu 16.04 and 18.04
For Ubuntu 14.04 no MongoDB packages so remove it from supported list.
Ubuntu 14.04 already has end of standard support according to the [1]
[1] https://wiki.ubuntu.com/Releases
> Unify mongodb version usage and remove Ubuntu 14.04 support

- launch
[Issue] N/A
[Problem] on clean Ubuntu 18.04, launch script reports error:
NameError: global name 'install_deb_package' is not defined
[Cause] install_deb_package is not defined when import_additional
function is called.
[Solution] Move import_additional to main.
[Test]
1. Before applying the patch do:
-sudo apt-get remove python-pip
2. You should see:
NameError: global name 'install_deb_package' is not defined
3. Apply the patch.
4. python-pip should be installed automatically and WATT should start.
> Fix "NameError: global name 'install_deb_package' is not defined"

- docker-compose.yml
[Issue] https://github.com/Samsung/WATT/issues/176
[Problem] WATT running locally uses mongod in version 4.2 but
WATT running in Docker environment uses 3.2.
[Solution] Bump mongod version to 4.2
[Test]
1. Clean all docker images related to mongo, for example
docker image rm mongo:3.2
./docker-run --rebuild
[Remarks] This image was alredy pushed to AWS in order to
include it in the upcoming watt release on AWS. They are
available at:
https://ap-south-1.console.aws.amazon.com/ecr/repositories/mongo_docker_repository/?region=ap-south-1
https://ap-south-1.console.aws.amazon.com/ecr/repositories/mongo_docker_repository/?region=ap-northeast-2
> [Docker] Bump mongod version to 4.2

- README.md
- watt-aws-instances-update.sh
[Issue] N/A
[Problem] Pushing docker images to two AWS instances
is time consuming
[Solution] Add --simultaneous-image-push to watt-aws-instances-update.sh
in order to push docker images in background.
Output from docker demon is cumulated which means that progress of
layer's push is reported to the same of line from different images.
> [Docker] Simultaneous docker image push

- routes/export.js
- routes/import.js
- routes/project.js
- test/project.js
Fix return value in routes/project.js
Fix return value in routes/import.js
Fix return value in routes/export.js
Fix return value in test/project.js
> Fix static analysis issues

- launch
[Issue] https://github.com/Samsung/WATT/issues/216
[Problem] dist folder has been removed from TAU in [1]
but WATT requires it for local samples and remote samples for
code.tizen.org.
[Solution] Build TAU while launching WATT
[Remarks] Requires [2].
[1] https://github.com/Samsung/TAU/commit/62a8d6b4d0f114e61d6ed384949e5565b19a6f1c
[2] https://github.com/Samsung/TAU/pull/630
> Let launch script build TAU

- .gitmodules
[Issue] https://github.com/Samsung/TAU/issues/1177
[Problem] TAU 1.2 examples are not working
[Solution] Add TAU/1.2 as sumboule which points to latest
TAU 1.2 release https://github.com/Samsung/TAU/releases/tag/v.1.2.4
[TEST]
1. Build and run WATT
./launch --verbose --bypass_nacl_sdk --bypass_emscripten
2. Open samples in Browser
http://localhost:3000/demos?path=1.2%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fpresentation-views%2Flist%2Fmain%2Findex.html
http://localhost:3000/demos?path=1.2%2Fexamples%2Fmobile%2FUIComponents%2Fcomponents%2Fappbar%2Fmore-option-list-max-width.html
3. Open UIComponets app in Browser
http://localhost:3000/TAU/1.2/examples/mobile/UIComponents/ (Mobile)
http://localhost:3000/TAU/1.2/examples/wearable/UIComponents/ (Wearable)
Signed-off-by: Grzegorz …
> Add TAU/1.2

- Dockerfile
Links to Tizen Studio are dead. Remove them since there
is a need to update Tizen Studio and make it work in headless
environment (previously we had two versions to overcome this issue).
> Remove Tizen Studio support from docker
